language: python

# you can use a different version of Python 
python: "3.6"

# don't clone more than necessary
git:
  depth: 1

services:
  - mysql

env:
  - DJANGO=3.2.6 DB=mysql SECRET_KEY='TEST' DEBUG=True

# Install dependencies
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
    
# script to run tests. Script can have many commands, one per line.
script: 
  - coverage run --source='.' manage.py test polls

after_script:
  - bash <(curl -s https://codecov.io/bash)